name:             logging-facade
version:          0.3.1
synopsis:         Simple logging abstraction that allows multiple back-ends
description:      Simple logging abstraction that allows multiple back-ends
copyright:        (c) 2014-2021 Simon Hengel
author:           Simon Hengel <sol@typeful.net>
maintainer:       Simon Hengel <sol@typeful.net>
category:         System

github: sol/logging-facade

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base == 4.*
    - call-stack
    - transformers

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base == 4.*
      - logging-facade
      - hspec == 2.*
    build-tools: hspec-discover
